version: "2"
services:
  fmeserverdb:
    image: safesoftware/fmeserver-db:${BUILD}
    volumes:
      - database:/var/lib/postgresql/data
    labels:
      io.rancher.scheduler.affinity:host_label: role=core

  fmeservercore:
    image: safesoftware/fmeserver-core:${BUILD}
    volumes:
      - fmeserver:/data/fmeserverdata
      - testvolume:/test
    ports:
      - "25:7125"
      - 7078:7078
    hostname: fmeservercore
    depends_on: 
      - fmeserverdb
      - fmeserverqueue
    labels:
      io.rancher.scheduler.affinity:host_label: role=core

  fmeserverweb:
    image: safesoftware/fmeserver-web:${BUILD}
    volumes:
      - fmeserver:/data/fmeserverdata
    ports:
      - 80:8080
    environment:
      - EXTERNALHOSTNAME=${EXTERNAL_HOSTNAME}
    hostname: fmeserverweb
    depends_on: 
      - fmeservercore
    labels:
      io.rancher.scheduler.affinity:host_label: role=core
      
  fmeserverqueue:
    image: safesoftware/fmeserver-queue:${BUILD}
    hostname: fmeserverqueue
    volumes:
      - fmeserver:/data/fmeserverdata
    labels:
      io.rancher.scheduler.affinity:host_label: role=core
 
  fmeserverengine:
    image: safesoftware/fmeserver-engine:${BUILD}
    volumes:
      - fmeserver:/data/fmeserverdata
    depends_on: 
      - fmeservercore
    environment:
      - EXTERNALHOSTNAME=${EXTERNAL_HOSTNAME}
      - FME_ENV_ENGINE_QUEUES=ScaledEngines
    mem_reservation: ${MEMORY_RESERVATION}
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: role=core
   
  fmeserverenginescaler:
    image: safesoftware/fmeserver-engine:${BUILD}
    volumes:
      - fmeserver:/data/fmeserverdata
    depends_on: 
      - fmeservercore
    environment:
      - EXTERNALHOSTNAME=${EXTERNAL_HOSTNAME}
      - FME_ENV_ENGINE_QUEUES=Scaler
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: role=core
    
volumes:
   database:
      driver: local
   fmeserver:
      driver: local
 
