


version: "2"
services:
 fmeserverdb:
  image: safesoftware/fmeserver-db:17539
  volumes:
   - database:/var/lib/postgresql/data
  restart: always
  labels:
    io.rancher.scheduler.affinity:host_label: role=core

 fmeservercore:
  image: safesoftware/fmeserver-core:17539
  volumes:
   - fmeserver:/data/fmeserverdata
   - testvolume:/test
  ports:
   - "25:7125"
   - 7078:7078
  hostname: fmeservercore
  restart: always
  depends_on: 
   - fmeserverdb
  labels:
    io.rancher.scheduler.affinity:host_label: role=core

 fmeserverweb:
  image: safesoftware/fmeserver-web:17539
  volumes:
   - fmeserver:/data/fmeserverdata
  ports:
   - 80:8080
  environment:
   - EXTERNALHOSTNAME=localhost
  hostname: fmeserverweb
  restart: always
  depends_on: 
   - fmeservercore
  labels:
   io.rancher.scheduler.affinity:host_label: role=core
 
 fmeserverengine:
  image: safesoftware/fmeserver-engine:17539
  volumes:
   - fmeserver:/data/fmeserverdata
  restart: always
  depends_on: 
   - fmeservercore
  environment:
   - EXTERNALHOSTNAME=localhost
  labels:
   io.rancher.container.hostname_override: container_name
   io.rancher.scheduler.affinity:host_label: role=worker
   
fmeserverenginescaler:
  image: safesoftware/fmeserver-engine:17539
  volumes:
   - fmeserver:/data/fmeserverdata
  restart: always
  depends_on: 
   - fmeservercore
  environment:
   - EXTERNALHOSTNAME=localhost
  labels:
   io.rancher.container.hostname_override: container_name
   io.rancher.scheduler.affinity:host_label: role=core
    
volumes:
   database:
      driver: local
   fmeserver:
      driver: rancher-nfs
 